# Generated by Django 5.0 on 2023-12-19 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userblocked',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userblocked',
            name='blocked_user',
        ),
        migrations.RemoveField(
            model_name='userblocked',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='followed_user',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserBlocked',
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
